#!/usr/bin/env php
<?php
/*
 * Where the binary executes from, this file was mostly pinched from PHPUnit itself: https://github.com/sebastianbergmann/phpunit/commit/c5c0e0169682f5818fa954e8ec8fd8ab93179e23
 *
 */


if (version_compare('7.0.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of PHPUnit is supported on PHP 7.0 and PHP 7.1.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('PHPUNIT_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('PHPUNIT_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

if (!file_exists('./vendor/bin/phpunit')) {
    fwrite(
        STDERR,
        'PHPUnit could not be found in ./vendor/bin/phpunit' . PHP_EOL . PHP_EOL
    );

    die(1);
}

require PHPUNIT_COMPOSER_INSTALL;

$VCS = new IcyApril\WhatsChanged\Git();
$whatsChanged = new IcyApril\WhatsChanged\WhatsChanged($VCS);
$whatsChanged->testChanges();